title = LightCycles
author = Xlvisuals
description = Lightcycles is a 3D multiplayer Tron-style lightcycle racing game
allowed_mapgens = singlenode
default_mapgen = singlenode
disabled_settings = creative_mode, enable_damage
release = 1
